[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=nss74_db
database.username=postgres
database.password=root456

[master_properties]
sheet_path =   D:\ETL Collections\nss74\Round - 74 Report - 74_2.35\data\TABLE 4.xlsx

[nss_tables_for_etl]
nss.tables.unique.sheets=1
nss.tables.table.1.block.count=3

nss.tables.table.1.block.1.sheet=TABLE 4

nss.tables.table.1.block.1.header.names=indicator_code,state_code,frame_code
nss.tables.table.1.block.1.sheet.header.values=4,37,1

nss.tables.table.1.block.1.rows.seggregation.level.count=1
nss.tables.table.1.block.1.cols.seggregation.level.count=1

nss.tables.table.1.block.1.cols.seggregation.1.foreign=bac_code
nss.tables.table.1.block.1.cols.seggregation.1.loopValue=14
nss.tables.table.1.block.1.cols.seggregation.1.totalRows=1
nss.tables.table.1.block.1.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

nss.tables.table.1.block.1.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.1.block.1.rows.seggregation.1.foreignValue=2,2,2,2,2,2,2,2,2,2,2,2,2,2

nss.tables.table.1.block.1.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.1.block.1.rows.seggregation.1.foreignValue=1,1,1,1

nss.tables.table.1.block.1.rows.seggregation.1.foreign=enterprises_mixed_activity_type_code
nss.tables.table.1.block.1.rows.seggregation.1.foreignValue=1,2,3,4






nss.tables.table.1.block.1.row.start=7
nss.tables.table.1.block.1.row.end=20
nss.tables.table.1.block.1.col.start=C
nss.tables.table.1.block.1.col.end=P


# ======================================================
nss.tables.table.2.block.2.sheet=TABLE 4

nss.tables.table.2.block.2.header.names=indicator_code,state_code,frame_code
nss.tables.table.2.block.2.sheet.header.values=4,37,2

nss.tables.table.2.block.2.rows.seggregation.level.count=1
nss.tables.table.2.block.2.cols.seggregation.level.count=1


nss.tables.table.2.block.2.cols.seggregation.1.foreign=state_code
nss.tables.table.2.block.2.cols.seggregation.1.loopValue=23
nss.tables.table.2.block.2.cols.seggregation.1.totalRows=1
nss.tables.table.2.block.2.cols.seggregation.1.foreignValue=1,2,5,6,7,8,9,10,11,13,14,15,16,17,20,22,23,25,26,28,29,32,37

nss.tables.table.2.block.2.rows.seggregation.1.foreign=bac_code
nss.tables.table.2.block.2.rows.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

nss.tables.table.2.block.2.row.start=23
nss.tables.table.2.block.2.row.end=36
nss.tables.table.2.block.2.col.start=C
nss.tables.table.2.block.2.col.end=P


# ======================================================
nss.tables.table.3.block.3.sheet=TABLE 4

nss.tables.table.3.block.3.header.names=indicator_code,state_code,frame_code
nss.tables.table.3.block.3.sheet.header.values=4,37,3

nss.tables.table.3.block.3.rows.seggregation.level.count=1
nss.tables.table.3.block.3.cols.seggregation.level.count=1


nss.tables.table.3.block.3.cols.seggregation.1.foreign=state_code
nss.tables.table.3.block.3.cols.seggregation.1.loopValue=36
nss.tables.table.3.block.3.cols.seggregation.1.totalRows=1
nss.tables.table.3.block.3.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37

nss.tables.table.3.block.3.rows.seggregation.1.foreign=bac_code
nss.tables.table.3.block.3.rows.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14


nss.tables.table.3.block.3.row.start=39
nss.tables.table.3.block.3.row.end=52
nss.tables.table.3.block.3.col.start=C
nss.tables.table.3.block.3.col.end=P



