[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=nss74_db
database.username=postgres
database.password=root456

[master_properties]
sheet_path =   D:\ETL Collections\nss74\Round - 74 Report - 74_2.35\data\TABLE 4.xlsx

[nss_tables_for_etl]
nss.tables.unique.sheets=1
nss.tables.table.1.block.count=6

nss.tables.table.1.block.1.sheet=TABLE 4

nss.tables.table.1.block.1.header.names=indicator_code,state_code,frame_code
nss.tables.table.1.block.1.sheet.header.values=4,37,1

nss.tables.table.1.block.1.rows.seggregation.level.count=1
nss.tables.table.1.block.1.cols.seggregation.level.count=1

nss.tables.table.1.block.1.cols.seggregation.1.foreign=bac_code
nss.tables.table.1.block.1.cols.seggregation.1.loopValue=14
nss.tables.table.1.block.1.cols.seggregation.1.totalRows=1
nss.tables.table.1.block.1.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

# nss.tables.table.1.block.1.rows.seggregation.1.foreign=enterprises_type_code
# nss.tables.table.1.block.1.rows.seggregation.1.foreignValue=2,2,2,2,2,2,2,2,2,2,2,2,2,2

nss.tables.table.1.block.1.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.1.block.1.rows.seggregation.1.foreignValue=2

nss.tables.table.1.block.1.row.start=7
nss.tables.table.1.block.1.row.end=20
nss.tables.table.1.block.1.col.start=C
nss.tables.table.1.block.1.col.end=C
#--------------------------------------------------------------------------------------------------------
nss.tables.table.2.block.2.sheet=TABLE 4

nss.tables.table.2.block.2.header.names=indicator_code,state_code,frame_code
nss.tables.table.2.block.2.sheet.header.values=4,37,1

nss.tables.table.2.block.2.rows.seggregation.level.count=2
nss.tables.table.2.block.2.cols.seggregation.level.count=1

nss.tables.table.2.block.2.cols.seggregation.1.foreign=bac_code
nss.tables.table.2.block.2.cols.seggregation.1.loopValue=14
nss.tables.table.2.block.2.cols.seggregation.1.totalRows=1
nss.tables.table.2.block.2.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

nss.tables.table.2.block.2.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.2.block.2.rows.seggregation.1.foreignValue=1,1,1,1

nss.tables.table.2.block.2.rows.seggregation.2.foreign=enterprises_reporting_mixed_activity_type_code
nss.tables.table.2.block.2.rows.seggregation.2.foreignValue=1,2,3,4

nss.tables.table.2.block.2.row.start=7
nss.tables.table.2.block.2.row.end=20
nss.tables.table.2.block.2.col.start=D
nss.tables.table.2.block.2.col.end=G

# # ======================================================

nss.tables.table.3.block.3.sheet=TABLE 4

nss.tables.table.3.block.3.header.names=indicator_code,state_code,frame_code
nss.tables.table.3.block.3.sheet.header.values=4,37,2

nss.tables.table.3.block.3.rows.seggregation.level.count=1
nss.tables.table.3.block.3.cols.seggregation.level.count=1

nss.tables.table.3.block.3.cols.seggregation.1.foreign=bac_code
nss.tables.table.3.block.3.cols.seggregation.1.loopValue=14
nss.tables.table.3.block.3.cols.seggregation.1.totalRows=1
nss.tables.table.3.block.3.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

nss.tables.table.3.block.3.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.3.block.3.rows.seggregation.1.foreignValue=2

nss.tables.table.3.block.3.row.start=23
nss.tables.table.3.block.3.row.end=36
nss.tables.table.3.block.3.col.start=C
nss.tables.table.3.block.3.col.end=C
#--------------------------------------------------------------------------------------------------------
nss.tables.table.4.block.4.sheet=TABLE 4

nss.tables.table.4.block.4.header.names=indicator_code,state_code,frame_code
nss.tables.table.4.block.4.sheet.header.values=4,37,2

nss.tables.table.4.block.4.rows.seggregation.level.count=2
nss.tables.table.4.block.4.cols.seggregation.level.count=1

nss.tables.table.4.block.4.cols.seggregation.1.foreign=bac_code
nss.tables.table.4.block.4.cols.seggregation.1.loopValue=14
nss.tables.table.4.block.4.cols.seggregation.1.totalRows=1
nss.tables.table.4.block.4.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

nss.tables.table.4.block.4.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.4.block.4.rows.seggregation.1.foreignValue=1,1,1,1

nss.tables.table.4.block.4.rows.seggregation.2.foreign=enterprises_reporting_mixed_activity_type_code
nss.tables.table.4.block.4.rows.seggregation.2.foreignValue=1,2,3,4

nss.tables.table.4.block.4.row.start=23
nss.tables.table.4.block.4.row.end=36
nss.tables.table.4.block.4.col.start=D
nss.tables.table.4.block.4.col.end=G


# # ======================================================

nss.tables.table.5.block.5.sheet=TABLE 4

nss.tables.table.5.block.5.header.names=indicator_code,state_code,frame_code
nss.tables.table.5.block.5.sheet.header.values=4,37,3

nss.tables.table.5.block.5.rows.seggregation.level.count=1
nss.tables.table.5.block.5.cols.seggregation.level.count=1

nss.tables.table.5.block.5.cols.seggregation.1.foreign=bac_code
nss.tables.table.5.block.5.cols.seggregation.1.loopValue=14
nss.tables.table.5.block.5.cols.seggregation.1.totalRows=1
nss.tables.table.5.block.5.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

# nss.tables.table.5.block.5.rows.seggregation.1.foreign=enterprises_type_code
# nss.tables.table.5.block.5.rows.seggregation.1.foreignValue=2,2,2,2,2,2,2,2,2,2,2,2,2,2

nss.tables.table.5.block.5.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.5.block.5.rows.seggregation.1.foreignValue=2

nss.tables.table.5.block.5.row.start=39
nss.tables.table.5.block.5.row.end=52
nss.tables.table.5.block.5.col.start=C
nss.tables.table.5.block.5.col.end=C

#--------------------------------------------------------------------------------------------------------


nss.tables.table.6.block.6.sheet=TABLE 4

nss.tables.table.6.block.6.header.names=indicator_code,state_code,frame_code
nss.tables.table.6.block.6.sheet.header.values=4,37,3

nss.tables.table.6.block.6.rows.seggregation.level.count=2
nss.tables.table.6.block.6.cols.seggregation.level.count=1

nss.tables.table.6.block.6.cols.seggregation.1.foreign=bac_code
nss.tables.table.6.block.6.cols.seggregation.1.loopValue=14
nss.tables.table.6.block.6.cols.seggregation.1.totalRows=1
nss.tables.table.6.block.6.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14

nss.tables.table.6.block.6.rows.seggregation.1.foreign=enterprises_type_code
nss.tables.table.6.block.6.rows.seggregation.1.foreignValue=1,1,1,1

nss.tables.table.6.block.6.rows.seggregation.2.foreign=enterprises_reporting_mixed_activity_type_code
nss.tables.table.6.block.6.rows.seggregation.2.foreignValue=1,2,3,4

nss.tables.table.6.block.6.row.start=39
nss.tables.table.6.block.6.row.end=52
nss.tables.table.6.block.6.col.start=D
nss.tables.table.6.block.6.col.end=G


