[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=asuse_db
database.username=postgres
database.password=root456


[master_properties]
sheet_path = data\Data for eSankhyiki-QBUSE.xlsx


[asuse_tables_for_etl]
asuse.tables.unique.sheets=1

asuse.tables.table.1.block.1.sheet=Table-2

asuse.tables.table.1.block.count=1

asuse.tables.table.1.header.names=financial_year,quarter_code,frequency_code,state_code
asuse.tables.table.1.block.1.sheet.header.values=2026,1,2,37



asuse.tables.table.1.rows.seggregation.level.count=1
asuse.tables.table.1.cols.seggregation.level.count=1


asuse.tables.table.1.rows.seggregation.1.criteria=indicator_code
asuse.tables.table.1.rows.seggregation.1.values=47,40,41,42,48,46,49,50

asuse.tables.table.1.cols.seggregation.1.criteria=bac_code
asuse.tables.table.1.cols.seggregation.1.values=1,2,3,5


asuse.tables.table.1.row.start=4
asuse.tables.table.1.row.end=11
asuse.tables.table.1.col.start=P
asuse.tables.table.1.col.end=S








