[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=asuse_db
database.username=postgres
database.password=root456
database.tablename=asuse_fact_new_table_37

[master_properties]
sheet_path = D:\Others\diwakar\etl-files\ASUSE ETL\ASUSE-2025\Tables - ASUSE 2025\Table-37.xlsx

[tables_for_etl]
etl.tables.unique.sheets=1
etl.tables.table.1.block.count=3

etl.tables.table.1.block.1.sheet=Sheet1

etl.tables.table.1.block.1.header.names=indicator_code,sector_code
etl.tables.table.1.block.1.sheet.header.values=58,1

etl.tables.table.1.block.1.rows.seggregation.level.count=1
etl.tables.table.1.block.1.cols.seggregation.level.count=1

etl.tables.table.1.block.1.cols.seggregation.1.foreign=bac_code
etl.tables.table.1.block.1.cols.seggregation.1.loopValue=4
etl.tables.table.1.block.1.cols.seggregation.1.totalRows=4
etl.tables.table.1.block.1.cols.seggregation.1.foreignValue=1,2,3,4

etl.tables.table.1.block.1.rows.seggregation.1.foreign=using_internet_code
etl.tables.table.1.block.1.rows.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13

etl.tables.table.1.block.1.row.start=8
etl.tables.table.1.block.1.row.end=11
etl.tables.table.1.block.1.col.start=B
etl.tables.table.1.block.1.col.end=N

# ==================================Block-2=============================

etl.tables.table.2.block.2.sheet=Sheet1

etl.tables.table.2.block.2.header.names=indicator_code,sector_code
etl.tables.table.2.block.2.sheet.header.values=58,2

etl.tables.table.2.block.2.rows.seggregation.level.count=1
etl.tables.table.2.block.2.cols.seggregation.level.count=1

etl.tables.table.2.block.2.cols.seggregation.1.foreign=bac_code
etl.tables.table.2.block.2.cols.seggregation.1.loopValue=4
etl.tables.table.2.block.2.cols.seggregation.1.totalRows=4
etl.tables.table.2.block.2.cols.seggregation.1.foreignValue=1,2,3,4

etl.tables.table.2.block.2.rows.seggregation.1.foreign=using_internet_code
etl.tables.table.2.block.2.rows.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13

etl.tables.table.2.block.2.row.start=37
etl.tables.table.2.block.2.row.end=40
etl.tables.table.2.block.2.col.start=B
etl.tables.table.2.block.2.col.end=N

# ==================================Block-3=============================

etl.tables.table.3.block.3.sheet=Sheet1

etl.tables.table.3.block.3.header.names=indicator_code,sector_code
etl.tables.table.3.block.3.sheet.header.values=58,3

etl.tables.table.3.block.3.rows.seggregation.level.count=1
etl.tables.table.3.block.3.cols.seggregation.level.count=1

etl.tables.table.3.block.3.cols.seggregation.1.foreign=bac_code
etl.tables.table.3.block.3.cols.seggregation.1.loopValue=4
etl.tables.table.3.block.3.cols.seggregation.1.totalRows=4
etl.tables.table.3.block.3.cols.seggregation.1.foreignValue=1,2,3,4

etl.tables.table.3.block.3.rows.seggregation.1.foreign=using_internet_code
etl.tables.table.3.block.3.rows.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13

etl.tables.table.3.block.3.row.start=68
etl.tables.table.3.block.3.row.end=71
etl.tables.table.3.block.3.col.start=B
etl.tables.table.3.block.3.col.end=N