[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=asuse_db
database.username=postgres
database.password=root456
database.tablename=asuse_fact_new_table_3

[master_properties]
sheet_path = D:\Tables - ASUSE 2025\Table-3.xlsx

[tables_for_etl]
etl.tables.unique.sheets=1
etl.tables.table.1.block.count=3

etl.tables.table.1.block.1.sheet=Sheet1

etl.tables.table.1.block.1.header.names=indicator_code,sector_code
etl.tables.table.1.block.1.sheet.header.values=53,1

etl.tables.table.1.block.1.rows.seggregation.level.count=1
etl.tables.table.1.block.1.cols.seggregation.level.count=1

etl.tables.table.1.block.1.cols.seggregation.1.foreign= activity_code
etl.tables.table.1.block.1.cols.seggregation.1.loopValue= 50
etl.tables.table.1.block.1.cols.seggregation.1.totalRows= 50
etl.tables.table.1.block.1.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50

etl.tables.table.1.block.1.rows.seggregation.1.foreign =surveyed_units_code
etl.tables.table.1.block.1.rows.seggregation.1.foreignValue= 1,2,3

etl.tables.table.1.block.1.row.start=7
etl.tables.table.1.block.1.row.end=56
etl.tables.table.1.block.1.col.start=B
etl.tables.table.1.block.1.col.end=D

# ==================================Block-2=============================

etl.tables.table.2.block.2.sheet=Sheet1

etl.tables.table.2.block.2.header.names=indicator_code,sector_code
etl.tables.table.2.block.2.sheet.header.values=53,2

etl.tables.table.2.block.2.rows.seggregation.level.count=1
etl.tables.table.2.block.2.cols.seggregation.level.count=1

etl.tables.table.2.block.2.cols.seggregation.1.foreign=activity_code
etl.tables.table.2.block.2.cols.seggregation.1.loopValue=50
etl.tables.table.2.block.2.cols.seggregation.1.totalRows=50
etl.tables.table.2.block.2.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50


etl.tables.table.2.block.2.rows.seggregation.1.foreign=surveyed_units_code
etl.tables.table.2.block.2.rows.seggregation.1.foreignValue=1,2,3

etl.tables.table.2.block.2.row.start=60
etl.tables.table.2.block.2.row.end=109
etl.tables.table.2.block.2.col.start=B
etl.tables.table.2.block.2.col.end=D


# ==================================Block-3=============================

etl.tables.table.3.block.3.sheet=Sheet1

etl.tables.table.3.block.3.header.names=indicator_code,sector_code
etl.tables.table.3.block.3.sheet.header.values=53,3

etl.tables.table.3.block.3.rows.seggregation.level.count=1
etl.tables.table.3.block.3.cols.seggregation.level.count=1

etl.tables.table.3.block.3.cols.seggregation.1.foreign=activity_code
etl.tables.table.3.block.3.cols.seggregation.1.loopValue=50
etl.tables.table.3.block.3.cols.seggregation.1.totalRows=50
etl.tables.table.3.block.3.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50

etl.tables.table.3.block.3.rows.seggregation.1.foreign=surveyed_units_code
etl.tables.table.3.block.3.rows.seggregation.1.foreignValue=1,2,3

etl.tables.table.3.block.3.row.start=113
etl.tables.table.3.block.3.row.end=162
etl.tables.table.3.block.3.col.start=B
etl.tables.table.3.block.3.col.end=D