[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=asuse_db
database.username=postgres
database.password=root456
database.tablename=asuse_fact_new_table_8

[master_properties]
sheet_path = D:\Tables - ASUSE 2025\Table-8.xlsx

[tables_for_etl]
etl.tables.unique.sheets=1
etl.tables.table.1.block.count=2

etl.tables.table.1.block.1.sheet=Sheet1

etl.tables.table.1.block.1.header.names=indicator_code
etl.tables.table.1.block.1.sheet.header.values=5

etl.tables.table.1.block.1.rows.seggregation.level.count=1
etl.tables.table.1.block.1.cols.seggregation.level.count=1

etl.tables.table.1.block.1.cols.seggregation.1.foreign= sector_code
etl.tables.table.1.block.1.cols.seggregation.1.loopValue= 2
etl.tables.table.1.block.1.cols.seggregation.1.totalRows= 2
etl.tables.table.1.block.1.cols.seggregation.1.foreignValue=1,2

etl.tables.table.1.block.1.rows.seggregation.1.foreign = owner_education_level_code
etl.tables.table.1.block.1.rows.seggregation.1.foreignValue= 1,2,3,4,5,6,7

etl.tables.table.1.block.1.row.start=7
etl.tables.table.1.block.1.row.end=8
etl.tables.table.1.block.1.col.start=B
etl.tables.table.1.block.1.col.end=H

# ==================================Block-2=============================

etl.tables.table.2.block.2.sheet=Sheet1

etl.tables.table.2.block.2.header.names=indicator_code,sector_code
etl.tables.table.2.block.2.sheet.header.values=53,2

etl.tables.table.2.block.2.rows.seggregation.level.count=1
etl.tables.table.2.block.2.cols.seggregation.level.count=1

etl.tables.table.2.block.2.cols.seggregation.1.foreign=activity_code
etl.tables.table.2.block.2.cols.seggregation.1.loopValue=50
etl.tables.table.2.block.2.cols.seggregation.1.totalRows=50
etl.tables.table.2.block.2.cols.seggregation.1.foreignValue=1,2

etl.tables.table.2.block.2.rows.seggregation.1.foreign=no_of_proprietary_and_partnership_est_code
etl.tables.table.2.block.2.rows.seggregation.1.foreignValue=1,2

etl.tables.table.2.block.2.row.start=7
etl.tables.table.2.block.2.row.end=8
etl.tables.table.2.block.2.col.start=I
etl.tables.table.2.block.2.col.end=J