[database_details]
database.ip=10.24.89.9
database.port=5432
database.dbname=nss77_db
database.username=postgres
database.password=root456

[master_properties]
sheet_path = D:\data\nss77\nss77-round-2\Table A2R.xlsm

[nss77_tables_for_etl]
nss77.tables.unique.sheets=1
nss77.tables.table.1.block.count=2

nss77.tables.table.1.block.1.sheet=Table A2R

nss77.tables.table.1.block.1.header.names=indicator_code,sub_indicator_code
nss77.tables.table.1.block.1.sheet.header.values=2,1

nss77.tables.table.1.block.1.rows.seggregation.level.count=0
nss77.tables.table.1.block.1.cols.seggregation.level.count=3

nss77.tables.table.1.block.1.cols.seggregation.1.foreign=state_code
nss77.tables.table.1.block.1.cols.seggregation.1.loopValue=1
nss77.tables.table.1.block.1.cols.seggregation.1.totalRows=33
nss77.tables.table.1.block.1.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37


nss77.tables.table.1.block.1.cols.seggregation.2.foreign=occupational_category_code
nss77.tables.table.1.block.1.cols.seggregation.2.loopValue=11
nss77.tables.table.1.block.1.cols.seggregation.2.totalRows=33
nss77.tables.table.1.block.1.cols.seggregation.2.foreignValue=1,2,3


nss77.tables.table.1.block.1.cols.seggregation.3.foreign=asset_holding_class_code
nss77.tables.table.1.block.1.cols.seggregation.3.loopValue=11
nss77.tables.table.1.block.1.cols.seggregation.3.totalRows=1221
nss77.tables.table.1.block.1.cols.seggregation.3.foreignValue=1,2,3,4,5,6,7,8,9,10,11


nss77.tables.table.1.block.1.row.start=6
nss77.tables.table.1.block.1.row.end=1226
nss77.tables.table.1.block.1.col.start=D
nss77.tables.table.1.block.1.col.end=D


# ============2======================
nss77.tables.table.2.block.2.sheet=Table A2R

nss77.tables.table.2.block.2.header.names=indicator_code,sub_indicator_code
nss77.tables.table.2.block.2.sheet.header.values=2,2

nss77.tables.table.2.block.2.rows.seggregation.level.count=0
nss77.tables.table.2.block.2.cols.seggregation.level.count=3

nss77.tables.table.2.block.2.cols.seggregation.1.foreign=state_code
nss77.tables.table.2.block.2.cols.seggregation.1.loopValue=1
nss77.tables.table.2.block.2.cols.seggregation.1.totalRows=33
nss77.tables.table.2.block.2.cols.seggregation.1.foreignValue=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37


nss77.tables.table.2.block.2.cols.seggregation.2.foreign=occupational_category_code
nss77.tables.table.2.block.2.cols.seggregation.2.loopValue=11
nss77.tables.table.2.block.2.cols.seggregation.2.totalRows=33
nss77.tables.table.2.block.2.cols.seggregation.2.foreignValue=1,2,3


nss77.tables.table.2.block.2.cols.seggregation.3.foreign=asset_holding_class_code
nss77.tables.table.2.block.2.cols.seggregation.3.loopValue=11
nss77.tables.table.2.block.2.cols.seggregation.3.totalRows=1221
nss77.tables.table.2.block.2.cols.seggregation.3.foreignValue=1,2,3,4,5,6,7,8,9,10,11


nss77.tables.table.2.block.2.row.start=6
nss77.tables.table.2.block.2.row.end=1226
nss77.tables.table.2.block.2.col.start=G
nss77.tables.table.2.block.2.col.end=G

